eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

server:
  port: 8080
spring:
  cloud:
    inetutils:
      timeoutSeconds: 10
  application:
    name: Operators-Service
  datasource:
    password: _Imtheking007!
    url: jdbc:mysql://localhost:3306/operatordb
    username: root
